### ISSUE TITLE
Sensor interface 1 - Moisture sensor

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#7]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of the moisture sensor to a BBB in terms of Hardware and Software?

**Comment by toshinuraj** [comment]
1.caliberation problems,  it took time to figure out the values in terms of voltage 
2.no examples codes in the google for interfacing  moisture sensor with BBB
3.since the analog out of the moisture sensor varies from 0-3vdc added voltage divider circuit in between 
4.analysing analog read of the BBB  .took time t understand about the analog read of the BBB
